Repository ProjectEvergreen/create-evergreen-app, pull requests merged in 2018-10, with the labels that each got.

#14 Feature/issue 5 unit testing
  .circleci/config.yml
  .eslintrc
  .gitignore
  README.md
  karma-test-shim.js
  karma.conf.js
  package-lock.json
  package.json
  src/components/header/header.js
  src/components/header/header.spec.js
Labels: documentation, enhancement, help wanted

#18 Fix #15: Ignore shim via comment
  karma.conf.js
Labels: bug

#21 update version in lock file
  package-lock.json
Labels: chore

#19 Fix #4: improve logo image
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/header.spec.js
  src/components/header/logo.png
Labels: enhancement

#20 Fix #7: Generate manifest.json in output root
  src/index.html
  webpack.config.prod.js
Labels: enhancement

#24 compress logo
  src/components/header/logo.png
Labels: enhancement

#31 self install as part of CI
  .circleci/config.yml
  tasks/cea-install.js
Labels: chore

#27 enable performance budgets
  README.md
  webpack.config.prod.js
Labels: enhancement

#34 lint tasks as part of CI
  .circleci/config.yml
  package.json
Labels: bug

#38 add ES2018 syntax support for CEA
  .eslintrc
Labels: bug
