Repository ProjectEvergreen/create-evergreen-app, pull requests merged in 2018-11, with the labels that each got.

#39 Enhancement/issue 37 additional browser support karma
  .circleci/config.yml
  README.md
  karma.conf.js
  package-lock.json
  package.json
  yarn.lock
Labels: bug, chore, documentation, enhancement

#50 address inconsistent platform output of eslint
  .circleci/config.yml
  package.json
Labels: bug

#51 Adding customized package.json resolves #48, removing git clone
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  tasks/cea-install.js
  yarn.lock
Labels: enhancement

#42 Updating style, resolve #22
  README.md
  package-lock.json
  src/app/app.css
  src/app/app.js
  src/components/header/header.css
  src/components/header/header.js
  src/index.html
  src/pages/home/home.css
  src/pages/home/home.js
Labels: enhancement

#56 add D flag to npx, add lock files to project setup
  README.md
  tasks/cea-clean.js
  tasks/cea-install.js
Labels: bug

#58 Bug/issue 57 npx install fail dev dependencies
  README.md
  package-lock.json
  package.json
  tasks/cea-install.js
  tasks/copy-folder.js
  yarn.lock
Labels: 0.4.1, bug

#63 Chore/issue 61 refactor target directory creation
  tasks/cea-install.js
Labels: chore

#60 Adding missing gitignore for npx install, closes #59
  package.json
  tasks/cea-install.js
Labels: bug
